"""Draw the three 24x18 rock-paper-scissors gestures for the OLED."""

from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "ui" / "RpsIcons.h"
PREVIEW = ROOT / "docs" / "rps-icons-preview.png"
WIDTH, HEIGHT = 24, 18


def icon(kind: str) -> Image.Image:
    im = Image.new("1", (WIDTH, HEIGHT), 0)
    d = ImageDraw.Draw(im)
    if kind == "scissors":
        # Raised index and middle fingers make a wide, unmistakable V.
        d.polygon([(7, 9), (2, 2), (4, 1), (10, 8)], outline=1, fill=0)
        d.line([(2, 2), (7, 9)], fill=1)
        d.polygon([(13, 8), (19, 1), (21, 2), (17, 10)], outline=1, fill=0)
        d.line([(19, 1), (13, 8)], fill=1)
        d.polygon([(7, 8), (11, 7), (15, 9), (17, 12), (16, 16), (8, 16), (6, 12)], outline=1, fill=0)
        d.line([(8, 10), (11, 12)], fill=1)
        d.line([(10, 16), (10, 17), (15, 17)], fill=1)
    elif kind == "rock":
        # Four knuckles plus a thumb folded across a solid palm.
        d.polygon([(3, 7), (5, 5), (18, 5), (21, 8), (20, 13), (17, 16), (7, 16), (3, 13)], outline=1, fill=0)
        for x in (7, 11, 15):
            d.line([(x, 5), (x, 9)], fill=1)
        d.line([(4, 10), (16, 10), (19, 12)], fill=1, width=2)
        d.line([(7, 16), (7, 17), (16, 17)], fill=1)
    elif kind == "paper":
        # A flat open palm with four separate upright fingertips.
        d.line([(4, 13), (4, 4), (6, 3), (7, 4), (7, 9)], fill=1)
        d.line([(7, 9), (7, 2), (9, 1), (10, 2), (10, 8)], fill=1)
        d.line([(10, 8), (10, 2), (12, 1), (13, 2), (13, 8)], fill=1)
        d.line([(13, 8), (13, 3), (15, 2), (16, 3), (16, 9)], fill=1)
        d.line([(16, 9), (17, 6), (19, 6), (20, 8), (20, 13), (17, 16), (8, 16), (4, 13)], fill=1)
        d.line([(8, 16), (8, 17), (16, 17)], fill=1)
    else:
        raise ValueError(kind)
    return im


def packed(im: Image.Image) -> list[int]:
    # Hardware::Display::drawGlyph reads row-major MSB-first, with zero as ink.
    values = []
    for y in range(HEIGHT):
        for bx in range(WIDTH // 8):
            value = 0
            for bit in range(8):
                if not im.getpixel((bx * 8 + bit, y)):
                    value |= 1 << (7 - bit)
            values.append(value)
    return values


def main() -> None:
    kinds = ("scissors", "rock", "paper")
    icons = [icon(kind) for kind in kinds]
    lines = [
        "#pragma once", "", "#include <stdint.h>", "",
        "// Generated by tools/generate_rps_icons.py. 24x18, zero bits are visible ink.",
        "namespace Ui { namespace RpsIcons {",
        "constexpr uint8_t kWidth = 24;",
        "constexpr uint8_t kHeight = 18;",
    ]
    for kind, im in zip(kinds, icons):
        name = "k" + kind.capitalize()
        data = packed(im)
        lines.append(f"static const uint8_t {name}[{len(data)}] = {{")
        for start in range(0, len(data), 12):
            lines.append("    " + ", ".join(f"0x{value:02X}" for value in data[start:start + 12]) + ",")
        lines.append("};")
    lines.append("} }  // namespace Ui::RpsIcons")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Raw-size OLED strip at top; crisp enlarged copies below for pixel review.
    preview = Image.new("RGB", (384, 116), (0, 0, 0))
    for index, im in enumerate(icons):
        colored = Image.new("RGB", im.size, (0, 0, 0))
        colored.paste((255, 255, 255), mask=im.convert("L").point(lambda p: 255 if p else 0))
        x = 16 + index * 128
        preview.paste(colored, (x + 48, 8))
        preview.paste(colored.resize((96, 72), Image.Resampling.NEAREST), (x, 36))
    preview.save(PREVIEW)


if __name__ == "__main__":
    main()
