"""Convert the user-drawn gesture sheet to OLED bitmaps without resampling."""

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "ui" / "RpsIcons.h"
PREVIEW = ROOT / "docs" / "rps-icons-preview.png"
WIDTH, HEIGHT = 24, 18
SOURCE = ROOT / "assets" / "games" / "rps" / "gestures.png"
CELLS = {"paper": (0, 0), "rock": (24, 0), "scissors": (0, 18)}


def icon(kind: str) -> Image.Image:
    sheet = Image.open(SOURCE).convert("RGBA")
    if sheet.size != (48, 36):
        raise ValueError(f"Expected a 48x36 gesture sheet, got {sheet.size}")
    x, y = CELLS[kind]
    im = Image.new("1", (WIDTH, HEIGHT), 0)
    for row in range(HEIGHT):
        for col in range(WIDTH):
            r, g, b, alpha = sheet.getpixel((x + col, y + row))
            if alpha not in (0, 255) or (alpha and (r, g, b) not in ((0, 0, 0), (255, 255, 255))):
                raise ValueError("Expected opaque black/white or transparent pixels")
            im.putpixel((col, row), bool(alpha and r == 255))
    return im


def packed(im: Image.Image) -> list[int]:
    # Hardware::Display::drawGlyph reads row-major MSB-first, with zero as ink.
    values = []
    for y in range(HEIGHT):
        for bx in range(WIDTH // 8):
            value = 0
            for bit in range(8):
                if not im.getpixel((bx * 8 + bit, y)):
                    value |= 1 << (7 - bit)
            values.append(value)
    return values


def main() -> None:
    kinds = ("scissors", "rock", "paper")
    icons = [icon(kind) for kind in kinds]
    lines = [
        "#pragma once", "", "#include <stdint.h>", "",
        "// Generated by tools/generate_rps_icons.py from assets/games/rps gesture sheets.",
        "// All three gestures: gestures.png.",
        "// 24x18, zero bits are visible ink; source pixels are preserved exactly.",
        "namespace Ui { namespace RpsIcons {",
        "constexpr uint8_t kWidth = 24;",
        "constexpr uint8_t kHeight = 18;",
    ]
    for kind, im in zip(kinds, icons):
        name = "k" + kind.capitalize()
        data = packed(im)
        lines.append(f"static const uint8_t {name}[{len(data)}] = {{")
        for start in range(0, len(data), 12):
            lines.append("    " + ", ".join(f"0x{value:02X}" for value in data[start:start + 12]) + ",")
        lines.append("};")
    lines.append("} }  // namespace Ui::RpsIcons")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Raw-size OLED strip at top; crisp enlarged copies below for pixel review.
    preview = Image.new("RGB", (384, 116), (0, 0, 0))
    for index, im in enumerate(icons):
        colored = Image.new("RGB", im.size, (0, 0, 0))
        colored.paste((255, 255, 255), mask=im.convert("L").point(lambda p: 255 if p else 0))
        x = 16 + index * 128
        preview.paste(colored, (x + 48, 8))
        preview.paste(colored.resize((96, 72), Image.Resampling.NEAREST), (x, 36))
    preview.save(PREVIEW)


if __name__ == "__main__":
    main()
