#!/usr/bin/env python3
"""Generate the small Traditional Chinese bitmap font used by the OLED UI."""

from pathlib import Path
import sys


CHARACTERS = "".join(dict.fromkeys(
    "選單餵食清潔治療陪玩休息狀態飽心情健康生病正常"
    "等待孵化中無法使用了長大階段蛋幼鳥成按下執行返回尚未完成"
    "紀錄墓碑群領養新確定刪除請先已滿繼續死亡目前寵物"
    "接來探望園……？！一般睡眠省電年齡天時分"
    "猜拳共三回合開始剪刀石頭布你贏輸平手勝再左右"
    "不需查部念冊全遠送別後召留出發旅行囉謝的伴牠保存重試"
    "記憶音符住旋律換答對試一次五看完照順序推超正確箭"
))


def parse_bdf(path: Path):
    glyphs = {}
    current = None
    bitmap = []
    reading_bitmap = False

    with path.open("r", encoding="ascii", errors="strict") as source:
        for raw_line in source:
            line = raw_line.strip()
            if line.startswith("STARTCHAR "):
                current = {"encoding": None, "bbx": None, "dwidth": 12}
                bitmap = []
                reading_bitmap = False
            elif current is not None and line.startswith("ENCODING "):
                current["encoding"] = int(line.split()[1])
            elif current is not None and line.startswith("DWIDTH "):
                current["dwidth"] = int(line.split()[1])
            elif current is not None and line.startswith("BBX "):
                current["bbx"] = tuple(map(int, line.split()[1:5]))
            elif current is not None and line == "BITMAP":
                reading_bitmap = True
            elif current is not None and line == "ENDCHAR":
                if current["encoding"] is not None:
                    current["bitmap"] = bitmap
                    glyphs[current["encoding"]] = current
                current = None
                reading_bitmap = False
            elif current is not None and reading_bitmap:
                bitmap.append(int(line, 16))
    return glyphs


def render_12x12(glyph):
    width, height, x_offset, y_offset = glyph["bbx"]
    source_bytes = (width + 7) // 8
    rows = [[False] * 12 for _ in range(12)]
    top = 11 - (y_offset + height)

    for source_y, source_bits in enumerate(glyph["bitmap"]):
        for source_x in range(width):
            bit_index = source_bytes * 8 - 1 - source_x
            if source_bits & (1 << bit_index):
                x = x_offset + source_x
                y = top + source_y
                if 0 <= x < 12 and 0 <= y < 12:
                    rows[y][x] = True

    encoded = []
    for row in rows:
        for byte_start in (0, 8):
            value = 0xFF
            for bit in range(8):
                x = byte_start + bit
                if x < 12 and row[x]:
                    value &= ~(0x80 >> bit)
            encoded.append(value)
    return encoded


def write_header(path: Path, glyphs):
    lines = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "#include <stdint.h>",
        "",
        "// Project-specific 12x12 subset of WenQuanYi Bitmap Song.",
        "// Source: https://github.com/olikraus/u8g2/blob/master/tools/font/bdf/wenquanyi_9pt.bdf",
        "// License: GPL v2 with the WenQuanYi font embedding exception.",
        "// Generated by tools/generate_ui_font.py; do not edit by hand.",
        "namespace UiFont12 {",
        "struct Glyph { uint16_t codepoint; const uint8_t* bitmap; };",
        "",
    ]

    entries = []
    for character in CHARACTERS:
        codepoint = ord(character)
        if codepoint not in glyphs:
            raise RuntimeError(f"missing U+{codepoint:04X} ({character}) in source font")
        data = render_12x12(glyphs[codepoint])
        name = f"kGlyph{codepoint:04X}"
        lines.append(f"const uint8_t {name}[24] PROGMEM = {{")
        for offset in range(0, len(data), 8):
            values = ", ".join(f"0x{value:02X}" for value in data[offset:offset + 8])
            lines.append(f"    {values},")
        lines.append("};")
        entries.append((codepoint, name))

    lines.extend(["", "const Glyph kGlyphs[] = {"])
    for codepoint, name in sorted(entries):
        lines.append(f"    {{0x{codepoint:04X}, {name}}},")
    lines.extend([
        "};",
        "constexpr uint16_t kGlyphCount = sizeof(kGlyphs) / sizeof(kGlyphs[0]);",
        "constexpr uint8_t kWidth = 12;",
        "constexpr uint8_t kHeight = 12;",
        "}  // namespace UiFont12",
        "",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate_ui_font.py SOURCE.bdf OUTPUT.h")
    source = Path(sys.argv[1])
    output = Path(sys.argv[2])
    write_header(output, parse_bdf(source))


if __name__ == "__main__":
    main()
